# This file contains the configuration for the home (default path) page.

# Everything in this file is listen in chronological order to how they appear on the page.
# Both HTML and Markdown are supported in most values.


# The large text at the top of the page.
title: "Calendar"
# The smaller text below the title.
subtitle: ""

# Google Calendar embed link
embed: "https://calendar.google.com/calendar/embed?height=600&wkst=1&ctz=America%2FLos_Angeles&mode=MONTH&showPrint=0&title=ChainLynx%20Calendar&src=Y180OWE3Yzg2MzI5NzE3ZmUwMDgzN2U2ZmQwMDBhYmI4YjIxMTg2ZjJkN2M4ZTM2Yzc5NDZmMzUwNmIzYjNjOWIyQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&src=Y181YzkxNjIxZmFkYzI1ZWY1YTJjMTRkMWEwMDJjYmVkNDA0MGM4OWRjODgwYWQ5MjI5NWY1MTVkZmI3ZDFkYTU5QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&src=Y19jOTE5ZTY1ZGZjMThlYmMyZGQxOTA3NzhiZTdjNzQ2YjRjMDk1MTVjM2M2MWJjOGRmNDNhMzk5NTI5MGZjNGIwQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&src=Y19kMjNhZGFlNGQ1NTYyNTNhM2I5ZjEyYjhiMTVkNTNjMGNhYzYyMWI5YzFiN2I5NjNmZDA0MjJmODVkNWNjNGI2QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&src=Y19jOThhNjU2M2Q1ZjE1OTU4NzUzZGJlOTNkY2E5ZDc1NDcxYTJmZjE2YTdmNzQwMjFkNjk0NjQwOWRiN2MzNzkzQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&src=Y18zZDU1ZTQ2ZmE0OTUwNGUyYjJlNmE4ZDNjNjA2YWYxN2VhZTM3ZmY3NmI3ZTI0NWQ1ZmVkMTM5MzJlZDhmNjM2QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&color=%234285f4&color=%23ad1457&color=%23ef6c00&color=%23c0ca33&color=%23a79b8e&color=%23e67c73"